apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-pi-{{ ds }}-{{ task_instance.try_number }}"
  namespace: default
spec:
  ttlSecondsAfterFinished: 30
  type: Python
  pythonVersion: "3"
  mainApplicationFile: local:///opt/code/etl/run-airflow.py
  mode: cluster
  image: "dpinedaj/spark-python-base:1.0"
  imagePullPolicy: Always
  sparkVersion: "3.2.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.2.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"